### ISSUE TITLE
The connection to 'localhost' failed

### ISSUE THREAD

**Issue by Steeve13011** [OfficeDev/Outlook-Add-in-SSO#17]
I filled in my Azure Active Directory settings in the Web.Config and tested the Office-Add-in-ASPNET-SSO-master \ Office-Add-in-ASPNET-SSO-master \ Before project. When I run the application in DEBUG mode I have the following error message:
![SSO_Sample_error](https://user-images.githubusercontent.com/66310200/102104615-ad30b400-3e2e-11eb-8f89-82ac184b87be.png)

I analyzed the error using Fiddler and got the following error message:
![SSO_Sample_error2](https://user-images.githubusercontent.com/66310200/102105451-bb330480-3e2f-11eb-8767-0d3a9f744743.png)

I tried the following command in using power shell but I always the same error :
**_CheckNetIsolation LoopbackExempt -a -n=”microsoft.win32webviewhost_cw5n1h2txyewy"_**

Thanks you for your help

**Comment by ElizabethSamuel-MSFT** [comment]
@Steeve13011 Thanks for raising this issue.

@davidchesnut Can you take a look and help direct?

Thanks.

**Comment by davidchesnut** [comment]
Hi @Steeve13011,

Can you try using a browser to go to https://localhost:44355/ ? You should be able to see the add-ins task pane in a browser. If it is not working it would be useful to see if any additional info is provided. 

Thanks!
David

**Comment by Steeve13011** [comment]
Hi David,

The site Web https://localhost:44355/ works. When the site is launched with Excel project I get the error message. The work station has Windows 10 Professional with the latest update and the latest version of Edge.

Thanks you for your help.
Steeve

**Comment by davidchesnut** [comment]
Hi @Steeve13011, 

Ok looking some more into this... I built the sample and it runs fine, so it seems unlikely there is any bug in the sample.

**Can you try running "yo office"** at the command line and just build a simple add-in and run it? If it doesn't run, then it means Excel for some reason isn't loading any add-ins when sideloaded. 
If the problem is in Excel, [I would clear the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache) by deleting the WEF folder. Then see if that fixes the problem.
Another option to try is see if you can [sideload the add-in in Excel on the web](https://docs.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing). If it works online, then again, this would point to Excel on Windows probably having something wrong in the cache.

Hope this helps,
David

**Comment by Steeve13011** [comment]
Hi David,

I found a solution. In fact, there isn't any bug in the sample. I configured the solution like this :
[cid:image001.png@01D6D45E.37319920]

I think it is necessary to start the 2 projects at the same time to avoid conflicts with IIS Express. Maybe it would be interesting if you add this procedure in your read me document. Without this configuration of the solution, this problem I reproduced on two different workstations.

Best regards,
Steeve
