### ISSUE TITLE
DialogError and Authentication dialog does not automatically close.

### ISSUE THREAD

**Issue by KarlMaynardDK** [OfficeDev/Outlook-Add-in-SSO#2]
Having installed and got this example running, by following the instructions in the ReadMe.md.

I was able to select a mail item from the launched OWA window, see and click the option to "Choose attachments". I was then able to select an attachment and click on the "Save Selected" button in the add-ins pane. This opened a dialog for me to "login to access onedrive"

However the authentication would always fail - after I logged into my O365 account, the authentication dialog would redirect to the MessageRead.html page (which showed nothing but a blank page).

In the add-in's pane, an error was showing indicating a "DialogError" - no helpful information could be seen in the browsers javascript console.

After debugging, the code in the MessageRead.html just did not seem to run.

After reading through the article "Create an ASP.NET Office Add-in that uses single sign-on (preview)" there is a section relating to granting consent to the add-in (required due to the side loading).

This section states "If the add-in isn't running in Visual Studio, press F5 to run it. It needs to be running in IIS for this procedure to complete smoothly."

I ran the solution in VS2017, and then called the consent url again;

https://login.microsoftonline.com/common/oauth2/authorize?client_id={id}&state=12345&response_type=code

....after doing this, WITH THE APPLICATION RUNNING, the example worked as expected - or at least so i thought.

After a nights rest, i restarted my pc and was back to the same issue.... "DialogError" !!

It does seem that it works a bit better in the Outlook client (windows), or by using an incognito window.

**Comment by jasonjoh** [comment]
Thanks for the report Karl. I'll have a look and see if I can reproduce this. At the time this was updated to use SSO, only desktop Outlook supported it, and that's all I tested with :). Since OWA enabled support for SSO I haven't had a chance to go back and validate. This gives me a good excuse.

**Comment by KarlMaynardDK** [comment]
You are more than welcome Jason :) 

Let me know if there is anything I can do with regards more information, debugging, testing...

**Comment by jasonjoh** [comment]
I think you're seeing a couple of different issues. I'll try to explain. :)

The demo tries to do single-signon first. If that fails, then you would get the pop up to sign in. Single-signon is the scenario that requires you to manually go to provide consent using the consent URL.

So I think what you're seeing is:

- You run the add-in. SSO fails due to no prior consent, then you fall into the pop-up scenario.
- Pop-up fails with DialogError. (I think there may be an issue with the office.helpers.js library the sample uses.)
- You manually browse to the consent URL and provide consent.
- Now when you run the add-in, SSO works and you never get the prompt.
- A day later, returning to the add-in, SSO stops working, you get the prompt, and back to DialogError.

So the problems I think are:

1. DialogError from office.helpers.js. I'm trying to track this down but it seems like it might be an issue in the library.
1. SSO consent expiring - this shouldn't happen as far as I know. I'm making some updates to the sample to better follow the SSO experience that might help your issue.

**Comment by KarlMaynardDK** [comment]
That makes sense - it certainly explains what we were seeing with it working one moment, then not the next. Let me know if there is anything more  I can do to help.

**Comment by davidchesnut** [comment]
Office js helpers was removed, and the sample is moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO There shouldn't be any issues related to Office js helpers now.
